# Generated by Django 4.0.3 on 2022-03-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOpenDateTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day_of_week', models.CharField(choices=[('0', 'Mon'), ('1', 'Tue'), ('2', 'Wed'), ('3', 'Thu'), ('4', 'Fri'), ('5', 'Sat'), ('6', 'Sun')], max_length=1, null=True)),
                ('start_time', models.IntegerField(default=0, max_length=30, null=True)),
                ('end_time', models.IntegerField(default=0, max_length=30, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_date_times', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('restaurants', models.ManyToManyField(related_name='collections', to='restaurant.restaurant')),
            ],
        ),
    ]
